<template>
  <div v-if="toast.show" :class="`tr-alert tr-alert-${toast.variant}`" class="scale-in-hor-left text-white">
    <div v-if="toast.hasSideBar" class="payment"
    >
      <GridLoader/>
    </div>
    <div v-if="!toast.hasSideBar" class="sidebar-alert"
         :class="`sidebar-${toast.variant}`"
    ></div>
    <div class="main">
      <p class="param-md text-white mb-0 font-weight-bold">
        {{ toast.title }}
      </p>
      <p class="param-sm mb-0 ">
        {{ toast.message }}
      </p>

    </div>
    <div v-if="toast.hasAction" class="action">
      <a v-if="toast.actions === 'Check'" target="_blank" class=" tr-green param-md font-weight-bolder"
         :href="`https://etherscan.io/address/${$cookies.get('account')}`">{{ actions }}</a>
      <a v-if="toast.actions === 'tryAgain'" @click="$router.push(localePath('/forest/addTree'))"
         class="pointer-event tr-green param-md font-weight-bolder"> Try again</a>
    </div>
    <div class="close">
      <span class="pointer-event" @click="exitToast">
        X
      </span>
    </div>
    <b-progress-bar :value="value" max="100" variant="success" animated striped>
    </b-progress-bar>
  </div>
</template>

<script>
import GridLoader from 'vue-spinner/src/GridLoader.vue'

export default {
  name: "AlertTreejer",
  components: {GridLoader},
  data() {
    return {
      toast: this.$store.state.toast,
      timer: 0,
      value: 0,
      max: 100
    }
  },
  methods: {
    exitToast() {
      this.$store.commit('toast/SET_TOAST', {
        show: false
      })
    },
    startTimer() {
      let self = this;
      let timer = setInterval(function () {
        self.value += 1;
        if (self.value >= self.max) clearInterval(timer);
      }, 50);
    }
  },
  mounted() {
    if (this.toast.hasDuration) {
      let self = this

      this.startTimer();
      this.$nextTick(() => {
        setTimeout(() => {
          this.$store.commit('toast/SET_TOAST', {
            show: false
          })
        }, 6000)
      })
    }
  }
}

</script>

<style scoped lang="scss">
.tr-alert {
  box-shadow: 0px -2px 7px rgba(0, 0, 0, 0.25);
  z-index: +99999;
  position: fixed;
  bottom: 5px;
  width: 368px;
  height: 64px;
  left: 5px;
  background: #212121;
  border-radius: 6px;
  display: flex;
  align-items: center;
  font-family: MontserratAlternates-Medium;

  .progress-bar.bg-success {
    position: absolute;
    top: -5px;
    height: 5px;
    left: 0;
    border-radius: 6px;
    background-color: #4d5b51 !important;

  }

  .main {
    padding: 32px 15px;
  }

  .action {
    position: absolute;
    right: 25px;
  }

  .sidebar-alert {
    width: 24px;
    height: 64px;
    border-radius: 6px 0px 0px 6px;
  }

  .sidebar-success {
    background: #67B68C;

  }

  .sidebar-danger {
    background: #D04F45;

  }

  .payment {
    width: 75px;
    height: 64px;
    padding: 5px;

  }

  .close {
    position: absolute;
    position: absolute;
    right: 0;
    top: 0;
    font-size: 12px;
    color: white;
    background: transparent;
    padding: 5px;
  }

}

.scale-in-hor-left {
  -webkit-animation: scale-in-hor-left 0.3s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
  animation: scale-in-hor-left 0.3s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-9-7 19:25:57
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-in-hor-left
 * ----------------------------------------
 */
@-webkit-keyframes scale-in-hor-left {
  0% {
    -webkit-transform: scaleX(0);
    transform: scaleX(0);
    -webkit-transform-origin: 0% 0%;
    transform-origin: 0% 0%;
    opacity: 1;
  }
  100% {
    -webkit-transform: scaleX(1);
    transform: scaleX(1);
    -webkit-transform-origin: 0% 0%;
    transform-origin: 0% 0%;
    opacity: 1;
  }
}

@keyframes scale-in-hor-left {
  0% {
    -webkit-transform: scaleX(0);
    transform: scaleX(0);
    -webkit-transform-origin: 0% 0%;
    transform-origin: 0% 0%;
    opacity: 1;
  }
  100% {
    -webkit-transform: scaleX(1);
    transform: scaleX(1);
    -webkit-transform-origin: 0% 0%;
    transform-origin: 0% 0%;
    opacity: 1;
  }
}

@keyframes flip-horizontal-bottom {
  0% {
    -webkit-transform: rotateX(0);
    transform: rotateX(0);
  }
  100% {
    -webkit-transform: rotateX(-180deg);
    transform: rotateX(-180deg);
  }
}


</style>
