
query fundersSorted($first: Int!, $skip: Int!, $orderBy: String!, $orderDirection: String) {
  funders(first: $first, skip: $skip, orderBy: $orderBy, orderDirection: $orderDirection) {
    id
    treeCount
  }

}