
query plantersSorted($first: Int!, $skip: Int!, $orderBy: String!, $orderDirection: String) {
  planters(first: $first, skip: $skip, orderBy: $orderBy, orderDirection: $orderDirection) {
    id
    verifiedPlantedCount
    plantedCount
    invitedCount
  }

}