query TreesBySoldType($first: Int!, $skip: Int!, $soldType: Int!, $orderBy: String!, $orderDirection: String!) { 
  trees(first: $first, skip: $skip, orderBy: $orderBy, orderDirection: $orderDirection
    where: {soldType: $soldType, owner_not: null}
  ) {
    id
    owner {
      id
    }
    treeSpecsEntity{
      imageFs
    }
    symbol {
      crownColor
    }
  }
}
