 {
  tree(id: $id) {
    id
    planter{
      id
    }
    owner{
      id
    }
    treeType
    mintStatus
    countryCode
    provideStatus
    treeStatus
    plantDate
    birthDate
    treeSpecsEntity{
      id
      name
      description
      externalUrl
      imageFs
      imageHash
      symbolFs
      symbolHash
      animationUrl
      diameter
      latitude
      longitude
      attributes
    }
  }
 }

